apiVersion: v1
kind: Service
metadata:
  name: node-service
spec: 
  ports:
  - port: {{.Values.intPort}}
    targetPort: {{.Values.nodeDeployPort}}
    protocol: TCP
  selector:
    name: node
  type: LoadBalancer
 