apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: node
  template: 
    metadata: 
      labels:
        name: node
    spec:
      containers: 
      - name: node
        image: aakash2707/node_es:v16.0
        ports:
        - containerPort: 8080